### PR TITLE
Feature/pseudo header

### PR DESCRIPTION
**Pull request by xcir**

### CODE REVIEW

**Comment by gquintard** [comment]
I'm good, with the scheme part, but I'd prefer to avoid noadd. Varnishtest can decode the index and check if it's a pseudo header.

Thoughts?

**Comment by xcir** [comment]
I'll try to implement to check encoded header.
But, I think noadd can also use the other.
 - missing required pseudo header.(abnormal pattern)

**Comment by gquintard** [comment]
True, that makes sense. Merging.

Don't worry then, there are more pressing issue :-)

**Comment by xcir** [comment]
I was changed two.
- pseudo header sort order
- check the pseudo header at -hdr, -idxHdr, litIdxHdr, -litHdr

**Comment by gquintard** [comment]
Oh, wait a minute, the check isn't right anyway, because the state can change (we have no mutex here). Don't care about checking the header, "-noadd" will do for the moment.

**Comment by xcir** [comment]
Ok,
Sorry for the confusion.

**Comment by gquintard** [comment]
No problem, I forgot about why I didn't do it in the first place.

But thanks anyway, the rest of the branch is merged!

**Pull request closed without merging**
