### PR TITLE
Hundle status 100

### PR DESCRIPTION
**Pull request by flano-yuki**

### CODE REVIEW

**Comment by gquintard** [comment]
Well, I'm not sure I agree with this one (the discussion is open, of course).

A stream isn't supposed to be thrown away after the response with END_STREAM, so you are not supposed to reuse it.

And I don't think the "100" error code makes sense anymore in H/2, since we now have the RST frames.

**Comment by flano-yuki** [comment]
Thank you for your polite comments.

> A stream isn't supposed to be thrown away after the response with END_STREAM, so you are not supposed to reuse it.
yes.
My case is two HEADERS frames in a stream (the former is not setted END_STREAM). described in 
```
     HTTP/1.1 100 Continue            HEADERS
     Extension-Field: bar       ==>     - END_STREAM
                                        + END_HEADERS
                                          :status = 100
                                          extension-field = bar

     HTTP/1.1 200 OK                  HEADERS
     Content-Type: image/jpeg   ==>     - END_STREAM
     Transfer-Encoding: chunked         + END_HEADERS
     Trailer: Foo                         :status = 200
                                          content-length = 123
                                          content-type = image/jpeg
                                          trailer = Foo
```
https://tools.ietf.org/html/rfc7540#section-8.1.3

> And I don't think the "100" error code makes sense anymore in H/2, since we now have the RST frames.
Yes.
"100" will not be used in most cases.
However, someone might be trying to use the 1xx for other purposes.
https://github.com/w3c/preload/issues/38#issuecomment-200236033
( This is a discussion of extetion feature. You might not need to support )


I think, supporting 1xx by varnish / varnishtest  is not essential.
This is up to you. Please Close this if no need.

sorry my poor english.
Thank you very much for sparing your precious time for me.

**Comment by gquintard** [comment]
Oh, you are right. Your test is indeed valid. I will merge it, I need to think a bit more about the code.

Thanks for bringing this to my attention!

**Comment by gquintard** [comment]
Ok, so, I committed h2tests/h2_pseudo-hdrs.vtc that is almost exactly your vtc (the first rxresp becomes a rxhdrs).

I see the 100 status code as a fringe case that varnish will never issue, so I'd prefer to handle it manually in vtc than automatically in the code. But I'll ask phk what's his view on this.

Also, if you spot servers actually using 100 codes, I'd be happy to reconsider.

**Comment by flano-yuki** [comment]
OK!
It looks good

thanks a lot :)

**Pull request closed without merging**
